# Generated by Django 4.1.3 on 2023-06-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='email',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prenom',
            field=models.CharField(max_length=150),
        ),
    ]
