# Generated by Django 4.1.3 on 2023-06-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enregistrement', '0002_alter_inscription_email_alter_inscription_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='user',
        ),
    ]
